### ISSUE TITLE
Include default .htaccess for craft

### ISSUE THREAD

**Issue by alexyoung91** [ten4design/ten4-framework#8] opened 2015-02-05 10:35 UTC
.htaccess_craft for craft set ups and .htaccess_slim for slim set ups. Make changes in the readme for instructions on renaming etc

**Comment by alexyoung91** [comment] 2015-02-05 10:36
Or if the htaccess files share entries, maybe have one file and remove the appropriate portion

**Comment by andygrn** [comment] 2015-02-05 13:05
duplicate of #7

**Closed by andygrn** 2015-02-05 13:05 UTC
